version: '3.8'

services:
  backend:
    build: .
    image: ${DOCKER_USERNAME}/back-eval2:latest
    container_name: back-eval2
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    environment:
      - PORT=3000
